### ISSUE TITLE
Feature: Add theming functionality

### ISSUE THREAD

**Issue by Lamparter** [0x5bfa/FluentHub#328]
### Description and Motivation

Adds theming to FluentHub. This can be achieved by creating multiple files with different **Primer** resources that the user can select.

### Motivation & Context

Related: #158
Related: #163 

```[tasklist]
### Tasks
- [ ] Improve border and some of SolidColorBrushes which contains in FluentHubDefault.xaml theme resources to use system default theme resources.
- [ ] Add theme switching helper class methods
- [ ] Add various GitHub's official themes
- [ ] Display those themes in app appearance settings page
```

**Comment by onein528** [comment]
I copied and converted(argb -> hex) from here https://primer.style/primitives/colors

**Comment by onein528** [comment]
Do you expect that Files do like just changing background?
