### ISSUE TITLE
Code Quality: Introduce AppCenter analytics for FluentHub

### ISSUE THREAD

**Issue by 0x5bfa** [0x5bfa/FluentHub#418]
### Before you start...

- [X] Have you checked if a similar feature request has already been reported?

### Description

As the title.

```[tasklist]
### Tasks
- [ ] Create credential file contaning AppCenter identity ID and Secret
- [ ] Install dependencies
- [ ] Add tracker in certain C# code blocks
```
