### ISSUE TITLE
Feature: Show only `source` repositories in sidebar

### ISSUE THREAD

**Issue by Lamparter** [0x5bfa/FluentHub#490]
### 📄 Description

FluentHub tends to show archived/forked repositories in the sidebar. It would make sense for it to display source repos instead (i.e. repos that are _not_ forks and are _not_ archived)
For example, it displays [`lamparter/files`](https://github.com/Lamparter/Files) but _not_ [`lamparter/smarttap`](https://github.com/Lamparter/SmartTap) which I would rather it displayed. (_it's not like i'm going to be contributing to archived repositories anytime soon!_)

### ⚡ Required changes

<!--
Include a list of all required changes in the code, i.e. additions, subtractions as would be required by your proposal. These changes should be considered placeholders, so the naming is not as important as getting the concepts correct. If possible you should include some example (pseudo-)code that illustrates your proposal.
```csharp

```-->

_No answer provided_

### 👥 Intended Use-Case

The users can view their `source` repositories and not archived/forked ones.

### ✅ Tasks

#### High Priority
- [ ] User should not see archived repos
- [ ] User should not see forks
- [ ] User should only see `source` repos, like [`lamparter/smarttap`](https://github.com/Lamparter/SmartTap)



### 📸 Assets

![image](https://github.com/user-attachments/assets/8d0d3384-2d35-4b5c-a29f-27bf70a9821c)
